services:
  db:
    image: postgres:15
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: weather_data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: weather_api
    restart: always

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "5000:5000"

    env_file:
      - .env.docker

    volumes:
      - .:/app

volumes:
  postgres_data: